### ISSUE TITLE
Fails to initiatialize

### ISSUE THREAD

**Issue by selfagency** [dahnielson/parcel-plugin-workbox#12]
The plugin seems to be failing with the latest version of Vue.

```
Server running at http://localhost:1234
⚠️  Plugin parcel-plugin-workbox failed to initialize: Error: Cannot find module 'parcel-bundler/src/Logger'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:655:15)
    at Function.Module._load (internal/modules/cjs/loader.js:580:25)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (/Users/daniel/Dev/kifa-web/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/daniel/Dev/kifa-web/node_modules/parcel-plugin-workbox/index.js:5:16)
    at Module._compile (/Users/daniel/Dev/kifa-web/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
```

**Comment by FDiskas** [comment]
thanks
